name       : python-ifaddr
version    : 0.1.7
release    : 1
source     :
    - https://github.com/pydron/ifaddr/archive/refs/tags/0.1.7.tar.gz : e72a677a66411bfd2ca2157f8adbf27ad59ed36f6185365b263d7bb475a6240c
homepage   : https://github.com/pydron/ifaddr
license    : MIT
component  : programming.python
summary    : Python Library to enumerate all network interfaces
description: |
    ifaddr is a small Python library that allows you to find all the Ethernet and IP addresses of the computer.
builddeps  :
    - python-pytest-cov
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
